USE [JobRecommenderDb]
GO

/****** Object:  Table [dbo].[KeySkills]    Script Date: 13-10-2020 18:15:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KeySkills](
	[id] [int] NOT NULL,
	[keyskill] [nvarchar](50) NULL,
 CONSTRAINT [PK_KeySkills] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


